export { Component } from 'vue-class-component'
export { Vue } from 'vue'
export { Services } from '@/utils/services'
export { Notifications } from '@/utils/notifications'
export { qrGen } from '@/utils/qr-generator'
export { Modal } from '@/utils/Modal'
